name: Test SSH

on:
  push:
    branches:
      - main

env:
  HOST: "46.232.211.190"
  USERNAME: "zealot001"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run a on-line script
        run: echo "Connexion au serveur = $HOST avec user = $USERNAME et password = ${{ secrets.PASS }}"
        
      - name: ls -a via ssh v1
        uses: fifsky/ssh-action@master
        with:
          command: |
            ls -a
          host: $HOST
          user: $USERNAME
          pass: ${{ secrets.PASS}}
          
      - name: ls -a via ssh v2
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: ls -a
          host: $HOST
          username: $USERNAME
          password : ${{ secrets.PASS}}
