name: Test SSH

on:
  push:
    branches:
      - main

env:
  HOST: "melete.usbx.me"
  USERNAME: "zealot001"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run a on-line script
        run: echo "Connexion au serveur = $HOST avec user = $USERNAME et password = ${{ secrets.PASS }}"

      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: $HOST
          username: $USERNAME
          password: ${{ secrets.PASS }}
          port: "22"
          script: whoami
